version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
      # target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - 5430:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
